name: VideoCap
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - pandas
  - pytorch
  - torchvision
  - opencv
  - pillow
  - sacrebleu
  - nltk
  - pip
  - pip:
      - scenedetect
      - joblib
